apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patchwork-file-data
  namespace: patchwork
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-rw
  volumeMode: Filesystem

